name: two_touch_mobile
description: two touch mobile application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.9.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation:
  flutter_secure_storage: ^3.3.3
  flushbar: ^1.10.4
  flutter_hooks: ^0.11.0
  hooks_riverpod: ^0.5.1
  hive: ^1.4.2
  hive_flutter: ^0.3.1
  http: ^0.12.2
  intl: ^0.16.1
  nfc_manager: ^1.3.2+4
  json_serializable: ^3.3.0
  loading_overlay: ^0.2.1
  logger: ^0.9.2
  state_notifier: ^0.5.0
  workmanager: ^0.2.0
  uuid : ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  build_runner: ^1.10.1
  freezed:
  hive_generator: ^0.7.1

flutter:
  uses-material-design: true
